# -*- coding: utf-8 -*-
"""day 3 divya

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upaRifIV-8wcM1Xymqo-70gKA_Z21iGW
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

#parameters
vocab_size = 1000  #number of unique words in your vocabulary
embedding_dim = 64 #size of word vector representations
max_length = 100   #max length of input sequences

# build the model
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length),
    LSTM(64),
    Dense(1, activation='sigmoid') #use'softmax'if you have multiple classes
])

#compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#prist model summary
model.summary()